<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-URDLST5" failures="1" tests="2" name="Default test(failed)(failed)(failed)" time="19.568" errors="0" timestamp="2022-10-21T23:09:15 IST">
  <testcase classname="TestCases.FailedTest" name="verifyLoginLogoTest" time="0.114">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.FailedTest.verifyLoginLogoTest(FailedTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginLogoTest -->
  <testcase classname="TestCases.FailedTest" name="verifyBotLogoTest" time="0.08"/>
  <testcase classname="TestCases.FailedTest" name="verifyTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyTitleTest -->
  <testcase classname="TestCases.FailedTest" name="loginToApp1Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp1Test -->
  <testcase classname="TestCases.FailedTest" name="verifyUrlTest" time="0.0">
    <ignored/>
  </testcase> <!-- verifyUrlTest -->
  <testcase classname="TestCases.FailedTest" name="loginToApp2Test" time="0.0">
    <ignored/>
  </testcase> <!-- loginToApp2Test -->
</testsuite> <!-- Default test(failed)(failed)(failed) -->
